1-module tasks added
js-tasks-ru/jsbasic-20210621_fenina-svetlana pull request #2
Opened 2021-07-03 18:37 UTC by svetache

2021-07-03 18:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-04 12:48 UTC, SinimaWath requested changes

2021-07-04 12:48 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let lowerStr = str.toLowerCase();
Это ведь const, если не изменяешь переменную

2021-07-04 12:48 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
`name.includes(" ") === false`, name.includes(" ") - уже возвращает true/false, и можно сократить до: `!name.includes(" ")`

2021-07-07 08:12 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-07 08:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-07 16:52 UTC, SinimaWath approved these changes
все круто )

2021-07-07 16:52 UTC, merged